### ISSUE TITLE
truncated input file?

### ISSUE THREAD

**Issue by dcopetti** [nanoporetech/medaka#176]
Hi,
I am running Medaka to resolve small indels from an assembly (>4 Gb, scaffolds, not obtained with Racon) and I get an error related to the input reads.
The command is
`medaka_consensus -i Rabiosa_G303_all_10kb_q7heads.fa -d test.fa -o test -t 50 -m r941_prom_high_g303`
and the error is:
```
7fd4d7253000-7fd4d7254000 ---p 00000000 00:00 0
7fd4d7254000-7fd4d7a54000 rw-p 00000000 00:00 0
7fd4d7a54000-7fd4d7a55000 ---p 00000000 00:00 0 [W::bgzf_read_block] EOF marker is absent. The input is probably truncated
samtools sort: truncated file. Aborting
Alignment pipeline failed.
Failed to run alignment of reads to draft.
```
with one file, this below is with another file that did not give problems when aligning with minimap2 outside of Medaka:
```
7f682e4a7000-7f682e4a8000 ---p 00000000 00:00 0 [W::bgzf_read_block] EOF marker is absent. The input is probably truncated
[bam_sort_core] merging from 0 files and 50 in-memory blocks...
/home/copettid/miniconda2/envs/medaka/bin/mini_align: line 159:  4287 Broken pipe             minimap2 ${ALIGN_OPTS} -t ${THREADS} -a ${REFERENCE}.mmi ${INPUT} -A ${MATCH_SCORE} -B ${MISMATCH_SCORE} -O ${GAP_OPEN} -E ${GAP_EXTEND}
      4288 Aborted                 (core dumped) | samtools view -@ ${THREADS} -T ${REFERENCE} ${FILTER} -bS -
      4289 Done                    | samtools sort -@ ${THREADS} ${SORT} -l 9 -o ${PREFIX}.bam -
Alignment pipeline failed.
Failed to run alignment of reads to draft.
```
What can be the cause for the error?

I also wonder if Medaka knows when to add the -I parameter to the minimap2 step, when the reference is larger than 4 Gb.
Thanks,
Dario

**Comment by dcopetti** [comment]
update:
I get the same error also with another file (.fq.gz) and running 
```
mini_align -i Rabiosa_G303_all_20kb_q8.fq.gz -r ../tgs_gapclosing/test.fa -P -m -p calls_to_test.bam -t 62
[...]
7fdf1436e000-7fdf1436f000 ---p 00000000 00:00 0
7fdf1436f000-7fdf14b6f000 rw-p 00000000 00:00 0
7fdf14b6f000-7fdf14b70000 ---p 00000000 00:00 0 [W::bgzf_read_block] EOF marker is absent. The input is probably truncated
[bam_sort_core] merging from 0 files and 62 in-memory blocks...
/home/copettid/miniconda2/envs/medaka/bin/mini_align: line 159: 24127 Broken pipe             minimap2 ${ALIGN_OPTS} -t ${THREADS} -a ${REFERENCE}.mmi ${INPUT} -A ${MATCH_SCORE} -B ${MISMATCH_SCORE} -O ${GAP_OPEN} -E ${GAP_EXTEND}
     24128 Aborted                 (core dumped) | samtools view -@ ${THREADS} -T ${REFERENCE} ${FILTER} -bS -
     24129 Done                    | samtools sort -@ ${THREADS} ${SORT} -l 9 -o ${PREFIX}.bam -
Alignment pipeline failed.
```

Medaka was installed via conda in its own environment

**Comment by dcopetti** [comment]
Hello,
Can anyone suggest me a possible solution? I tried different read files, I still get the same error. Can read length be an issue - too long of a read?
thanks

**Comment by mwykes** [comment]
Hi @dcopetti, 

Sorry for the slow response. We've recently upgrade to samtools 1.10, which perhaps does more thorough checks on the input sam. I've just come accross a similar error with samtools 1.10 which does not appear with samtools 1.9 (on the same data). Indeed as you suggest, telling minimap2 to write long cigar strings to the CG tag using the -L option fixes the issue. We'll get the fix released soon but in the mean time you could apply this patch to your mini_align script. 

after activating your conda env, run

`patch $(which mini_align) mini_align.patch`

with the patch
```35c35
< ALIGN_OPTS="-x map-ont"
---
> ALIGN_OPTS="-x map-ont -L"
```

Please let me know if this does indeed solve the problem on your data.

**Comment by dcopetti** [comment]
Thank you for the feedback @mwykes !
Just adding `-L` did not solve the problem, it worked once I pointed `mini_align` to a samtools 1.9 installation I have on the machine.

**Comment by mwykes** [comment]
Hi @dcopetti, thanks for the feedback. Since the -L option did not solve the problem on your data and the only way you could get it to work is by downgrading samtools, this issue could still affect other users. Would you be able to share your dataset (privately if needed) so we can try and debug it?

**Comment by bauerlev** [comment]
Hi @dcopetti, I also have encountered this issue. I'm newer to bioinformatics and I'm not sure how to specify using a different version of samtools than the default. Would you mind sharing how you did that? That version of samtools is currently installed on the hpcc I interact with.

**Comment by dcopetti** [comment]
hi @bauerlev,
I looked for another installation of samtools on that machine (`locate samtools`), chose one that is <1.10, made a new copy of the mini_align script, and added to all samtools commands in that script the path to the other version.
The final result looks like this:
```
$ grep -n flye /home/copettid/miniconda2/envs/medaka/bin/mini_align_st1.9
135:  /home/copettid/miniconda2/envs/flye_env/bin/flye-samtools faidx ${REFERENCE}
157:  /home/copettid/miniconda2/envs/flye_env/bin/flye-samtools view -@ ${THREADS} -T ${REFERENCE} ${FILTER} -bS - |
158:  /home/copettid/miniconda2/envs/flye_env/bin/flye-samtools sort -@ ${THREADS} ${SORT} -l 9 -o ${PREFIX}.bam - \
160:/home/copettid/miniconda2/envs/flye_env/bin/flye-samtools index -@ ${THREADS} ${PREFIX}.bam ${PREFIX}.bam.bai \
```
with the first number being the line number where I did the edits.
Some (bio)informaticians may shiver, but it works for me - I have very little informatics skills as well.
let us know how it goes!
