### ISSUE TITLE
Medaka_haploid_variant bug

### ISSUE THREAD

**Issue by jpn2021** [nanoporetech/medaka#287]
I tried running medaka_haploid_variant as described but now it seems to require a "-i" and a "-r" for defining the input fastq and fasta. After doing that I used the code below but ultimately the ouput (below) ends with an error "Failed to run alignment of reads to draft".

$ medaka_haploid_variant -i .basecalls.fastq -r reference.fa -t 8

```
Checking program versions
This is medaka 1.3.0
Program    Version    Required   Pass
bcftools   1.12       1.11       True
bgzip      1.12       1.11       True
minimap2   2.17       2.11       True
samtools   1.12       1.11       True
tabix      1.12       1.11       True
Aligning basecalls to reference
mini_align [-h] -r <reference> -i <fastq>

Align fastq/a formatted reads to a genome using minimap2.

    -h  show this help text.
    -r  reference, should be a fasta file. If correspondng minimap indices
        do not exist they will be created. (required).
    -i  fastq/a input reads (required).
    -I  split index every ~NUM input bases (default: 16G, this is larger
        than the usual minimap2 default).
    -f  force recreation of index file.
    -a  aggressively extend gaps (sets -A1 -B2 -O2 -E1 for minimap2).
    -P  filter to only primary alignments (i.e. run samtools view -F 2308).
        Deprecated: this filter is now default and can be disabled with -A.
    -A  do not filter alignments to primary alignments, output all.
    -n  sort bam by read name.
    -c  chunk size. Input reads/contigs will be broken into chunks
        prior to alignment.
    -t  alignment threads (default: 1).
    -p  output file prefix (default: reads).
    -m  fill MD tag.
    -s  fill cs(=long) tag.
    -X  only create reference index files.
    -x  log all commands before running.
    -M  match score
    -S  mismatch score
    -O  open gat penalty
    -E  extend gap penalty.
-r must be specified.
Failed to run alignment of reads to draft.
```

**Comment by jpn2021** [comment]
If I run `mini_align` outside of `medaka_haploid_variant` it seems to run successfully so the issue I would suspect is perhaps with the way in which `medaka_haploid_variant` calls `mini_align`

**Comment by cjw85** [comment]
Hi @jpn2021,

I am unable to reproduce this behaviour using a fresh conda environment with medaka v1.3.0:

```
mamba create -n medaka -c bioconda -c conda-forge medaka
conda activate medaka
medaka_haploid_variant -i reads.fastq.gz -r reference.fa -o conda_v1.3.0 -t 64
```

Can you ensure that you have created a new conda environment (or virtual environment if using the PyPI package) and installed medaka into that. Your symptom is similar to a historical issue another user has had that was solved by installation into a clean environment.

**Comment by jpn2021** [comment]
I did that and still get the same error. One difference I see is that my reads are just ".fastq" and not gziped

Perhaps the fastq file needs to be gziped with a particular software?

**Comment by jpn2021** [comment]
Also I noted that the latest conda version is 1.3.0 but it seems you made some recent fixed to a version 1.3.2.

**Comment by cjw85** [comment]
The read data being compressed or plaintext should not (and does not for me) make any difference. Can you check the output of

```
which medaka_haploid_variant
which mini_align
```

gives paths which you would expect for the newly created conda environment.

v1.3.2 was released this afternoon and contains a bug fix to `medaka_consensus` that would not be expected to change anything with respect to your issue.

**Comment by jpn2021** [comment]
Output of both of those seems fine:

/home/unix/miniconda3/envs/medaka/bin/medaka_haploid_variant
/home/unix/miniconda3/envs/medaka/bin/mini_align

I am in the medaka environment that was just created.

**Comment by jpn2021** [comment]
I found that if I first run `mini_align` with `-p calls_to_ref` then I can run `medaka_haploid_variant` and it seems happy using the files that were created. This would also seem to localize the problem to some way in which `medaka_haploid_variant` is calling `mini_align`.

After that a separate issue seems to appear with the `medaka variant` code. My filepath has spaces in it. The `mini_align` code and `medaka consensus` code don't seem to mind this but `medaka variant` within the `medaka_haploid_variant` code starts throwing errors. Running `medaka variant` separately outside `medaka_haploid_variant` does not seem to have any issues however and as long as I specify the same directory it seems content to use the files that were previously created by `mini_align` and `medaka consensus`.

**Comment by cjw85** [comment]
"My filepath has spaces in it"

This is very likely the root of your issue. Very many programs don't well handle spaces in filenames, and `medaka_haploid_variant` is one of those at the point that it is handing the filename to `mini_align`.

I would advise, if only for your own sanity, to not use spaces in filenames.

**Comment by jpn2021** [comment]
Thanks unfortunately it is something I cannot easily avoid. But most of `medaka_haploid_variant` does not seem to have issues. I would guess maybe there is an extra set of quotes perhaps around file paths in some parts of `medaka_haploid_variant` that make it work fine and missing extra quotes in other parts.

I'll continue with the rest of the pipeline for now.
